/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package grdm;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.File;
import grdm.*;


public class XmlParserTest {
    @Test public void testParse() throws Exception {
        File stylesheet = new File("src/test/java/Stylesheet.xsl");
        File xmlSource = new File("src/test/java/XmlSource.xml");
        File outputCsv = new File ( "src/test/java/output.csv");
        XmlParser xmlParser = new XmlParser(stylesheet);
        xmlParser.parse(xmlSource,outputCsv);

        //TODO: open csv file and run asserations on the content
    }
}
